#!/usr/bin/env bash
# This script configures the web server to listen to port 80.

file="/etc/nginx/sites-enabled/default"
sed -i "s/listen 8080 default_server;/listen 80 default_server;/g" "$file"
sed -i "s/listen \[::\]:8080 default_server ipv6only=on;/listen [::]:80 default_server ipv6only=on;/g" "$file"

service nginx restart
